# Site wide configuration

title: vDevices
description: "Consulting on Free, Open Source Software | Creating Quality Websites for Lawyers & Other Professionals"
logo: # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale:
url: http://www.vdevices.com

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: Pablo Carranza
  email:
  twitter:
  google:
    ad-client: 
    ad-slot: 
  bio: ... an aspiring writer (that used to be a lawyer). This website is Pablo's pathetic attempt to meld two of his intellectual intrigues into something that someone &ndash; somewhere &ndash; may actually find useful (as remote as that possibility may be).
  avatar: bio-photo.jpg # 160x160 px image for author byline
disqus-shortname: virtualdevices


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
